name: testing

# This trigger allows the workflow to be run manually
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib==3.5.3
        pip install numpy==1.23.3
        pip install pandas==1.4.4
        pip install scipy==1.9.1

    - name: Run pytest 
      run: |
        pytest py_FFT.py
        pytest py_DFT.py
